# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 632)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.titleLabel = QtGui.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(10, 0, 242, 39))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.titleLabel.setFont(font)
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.itemLabel = QtGui.QLabel(self.centralwidget)
        self.itemLabel.setGeometry(QtCore.QRect(10, 60, 26, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.itemLabel.setFont(font)
        self.itemLabel.setObjectName(_fromUtf8("itemLabel"))
        self.itemField = QtGui.QLineEdit(self.centralwidget)
        self.itemField.setGeometry(QtCore.QRect(50, 60, 651, 20))
        self.itemField.setObjectName(_fromUtf8("itemField"))
        self.itemLoadButton = QtGui.QPushButton(self.centralwidget)
        self.itemLoadButton.setGeometry(QtCore.QRect(710, 60, 75, 23))
        self.itemLoadButton.setObjectName(_fromUtf8("itemLoadButton"))
        self.itemInfoGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.itemInfoGroupBox.setGeometry(QtCore.QRect(9, 89, 782, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.itemInfoGroupBox.setFont(font)
        self.itemInfoGroupBox.setObjectName(_fromUtf8("itemInfoGroupBox"))
        self.label = QtGui.QLabel(self.itemInfoGroupBox)
        self.label.setGeometry(QtCore.QRect(10, 26, 46, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 54, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 82, 47, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 47, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 138, 34, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 166, 72, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 188, 79, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 216, 104, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 244, 63, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 272, 63, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 300, 39, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.itemInfoGroupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 328, 63, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.inStock = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.inStock.setGeometry(QtCore.QRect(120, 26, 331, 22))
        self.inStock.setObjectName(_fromUtf8("inStock"))
        self.category = QtGui.QComboBox(self.itemInfoGroupBox)
        self.category.setGeometry(QtCore.QRect(120, 54, 331, 22))
        self.category.setObjectName(_fromUtf8("category"))
        self.location = QtGui.QComboBox(self.itemInfoGroupBox)
        self.location.setGeometry(QtCore.QRect(120, 82, 331, 22))
        self.location.setObjectName(_fromUtf8("location"))
        self.supplier = QtGui.QComboBox(self.itemInfoGroupBox)
        self.supplier.setGeometry(QtCore.QRect(120, 110, 331, 22))
        self.supplier.setObjectName(_fromUtf8("supplier"))
        self.model = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.model.setGeometry(QtCore.QRect(120, 138, 331, 22))
        self.model.setObjectName(_fromUtf8("model"))
        self.isDiscontinued = QtGui.QCheckBox(self.itemInfoGroupBox)
        self.isDiscontinued.setGeometry(QtCore.QRect(120, 167, 16, 16))
        self.isDiscontinued.setText(_fromUtf8(""))
        self.isDiscontinued.setObjectName(_fromUtf8("isDiscontinued"))
        self.reorderLevel = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.reorderLevel.setGeometry(QtCore.QRect(120, 188, 331, 22))
        self.reorderLevel.setObjectName(_fromUtf8("reorderLevel"))
        self.tagetStockLevel = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.tagetStockLevel.setGeometry(QtCore.QRect(120, 216, 331, 22))
        self.tagetStockLevel.setObjectName(_fromUtf8("tagetStockLevel"))
        self.priceCAD = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.priceCAD.setGeometry(QtCore.QRect(120, 244, 331, 22))
        self.priceCAD.setObjectName(_fromUtf8("priceCAD"))
        self.priceUSD = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.priceUSD.setGeometry(QtCore.QRect(120, 272, 331, 22))
        self.priceUSD.setObjectName(_fromUtf8("priceUSD"))
        self.file3d = QtGui.QLineEdit(self.itemInfoGroupBox)
        self.file3d.setGeometry(QtCore.QRect(120, 300, 331, 22))
        self.file3d.setObjectName(_fromUtf8("file3d"))
        self.description = QtGui.QTextEdit(self.itemInfoGroupBox)
        self.description.setGeometry(QtCore.QRect(10, 350, 762, 101))
        self.description.setObjectName(_fromUtf8("description"))
        self.imageFrame = QtGui.QFrame(self.itemInfoGroupBox)
        self.imageFrame.setGeometry(QtCore.QRect(470, 30, 296, 296))
        self.imageFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.imageFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.imageFrame.setObjectName(_fromUtf8("imageFrame"))
        self.imageLabel = QtGui.QLabel(self.imageFrame)
        self.imageLabel.setGeometry(QtCore.QRect(0, 0, 291, 291))
        self.imageLabel.setText(_fromUtf8(""))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName(_fromUtf8("imageLabel"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(20, 560, 75, 23))
        self.saveButton.setDefault(False)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.clearButton = QtGui.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(110, 560, 75, 23))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuInventory = QtGui.QMenu(self.menubar)
        self.menuInventory.setObjectName(_fromUtf8("menuInventory"))
        self.menuDatabase = QtGui.QMenu(self.menubar)
        self.menuDatabase.setObjectName(_fromUtf8("menuDatabase"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_and_New = QtGui.QAction(MainWindow)
        self.actionSave_and_New.setEnabled(False)
        self.actionSave_and_New.setObjectName(_fromUtf8("actionSave_and_New"))
        self.actionPrint = QtGui.QAction(MainWindow)
        self.actionPrint.setObjectName(_fromUtf8("actionPrint"))
        self.actionEmail = QtGui.QAction(MainWindow)
        self.actionEmail.setObjectName(_fromUtf8("actionEmail"))
        self.actionCreate_new = QtGui.QAction(MainWindow)
        self.actionCreate_new.setObjectName(_fromUtf8("actionCreate_new"))
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionNew_Collection = QtGui.QAction(MainWindow)
        self.actionNew_Collection.setObjectName(_fromUtf8("actionNew_Collection"))
        self.actionLocations = QtGui.QAction(MainWindow)
        self.actionLocations.setObjectName(_fromUtf8("actionLocations"))
        self.actionCategories = QtGui.QAction(MainWindow)
        self.actionCategories.setObjectName(_fromUtf8("actionCategories"))
        self.actionSuppliers = QtGui.QAction(MainWindow)
        self.actionSuppliers.setObjectName(_fromUtf8("actionSuppliers"))
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionEmail)
        self.menuFile.addAction(self.actionClose)
        self.menuInventory.addAction(self.actionLoad)
        self.menuInventory.addAction(self.actionSave)
        self.menuInventory.addAction(self.actionSave_and_New)
        self.menuInventory.addSeparator()
        self.menuInventory.addAction(self.actionLocations)
        self.menuInventory.addAction(self.actionCategories)
        self.menuInventory.addAction(self.actionSuppliers)
        self.menuDatabase.addAction(self.actionSettings)
        self.menuDatabase.addAction(self.actionNew_Collection)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInventory.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.titleLabel.setText(_translate("MainWindow", "Inventory Details", None))
        self.itemLabel.setText(_translate("MainWindow", "Item", None))
        self.itemLoadButton.setText(_translate("MainWindow", "Load...", None))
        self.itemInfoGroupBox.setTitle(_translate("MainWindow", "Item Information", None))
        self.label.setText(_translate("MainWindow", "In Stock", None))
        self.label_2.setText(_translate("MainWindow", "Category", None))
        self.label_3.setText(_translate("MainWindow", "Location", None))
        self.label_4.setText(_translate("MainWindow", "Supplier", None))
        self.label_5.setText(_translate("MainWindow", "Model", None))
        self.label_6.setText(_translate("MainWindow", "Discontinued", None))
        self.label_7.setText(_translate("MainWindow", "Reorder Level", None))
        self.label_8.setText(_translate("MainWindow", "Target Stock Level", None))
        self.label_9.setText(_translate("MainWindow", "Price $CAD", None))
        self.label_10.setText(_translate("MainWindow", "Price $USD", None))
        self.label_11.setText(_translate("MainWindow", "3D File", None))
        self.label_12.setText(_translate("MainWindow", "Description", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.clearButton.setText(_translate("MainWindow", "Clear", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuInventory.setTitle(_translate("MainWindow", "Inventory", None))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionLoad.setText(_translate("MainWindow", "Load...", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_and_New.setText(_translate("MainWindow", "Save and New", None))
        self.actionPrint.setText(_translate("MainWindow", "Print", None))
        self.actionEmail.setText(_translate("MainWindow", "Email", None))
        self.actionCreate_new.setText(_translate("MainWindow", "Create new...", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionNew_Collection.setText(_translate("MainWindow", "New Database...", None))
        self.actionNew_Collection.setToolTip(_translate("MainWindow", "Create a new database", None))
        self.actionLocations.setText(_translate("MainWindow", "Locations...", None))
        self.actionCategories.setText(_translate("MainWindow", "Categories...", None))
        self.actionSuppliers.setText(_translate("MainWindow", "Suppliers...", None))

